/****
*
* TÍTULO: FUNÇÃO REMOVER TABELA/ARQUIVO
*
* AUTOR: LEVY MARLON SOUZA SANTIAGO
*
* DATA DA CRIAÇÃO: 20/06/2017
* ÚLTIMA MODIFICAÇÃO: 04/08/2017
*
* DESCRIÇÃO: ESTA FUNÇÃO IRÁ REMOVER UMA TABELA/ARQUIVO .ORI
*
* PARÂMETROS: - (char *): UM PONTEIRO A CHAR, QUE É O NOME DA TABELA
*
* VALORES DE RETORNO: ( 1) ARQUIVO DELETADO;
*					  (-1) ARQUIVO NÃO EXISTE;
*					  ( 0) ARQUIVO NÃO DELETADO - ERRO.
****/
int removerTabela(char *);

/****
*
* TÍTULO: FUNÇÃO DE VERIFICAÇÃO DE EXISTÊNCIA DO ARQUIVO
*
* AUTOR: LEVY MARLON SOUZA SANTIAGO
*
* DATA DA CRIAÇÃO: 20/06/2017
* ÚLTIMA MODIFICAÇÃO: 04/08/2017
*
* DESCRIÇÃO: ESTA FUNÇÃO IRÁ RETORNAR SE UM ARQUIVO EXISTE, DADO O CAMINHO DO MESMO.
*
* PARÂMETROS: - (caminho): UM PONTEIRO A CHAR, QUE SERÁ O CAMINHO DE UM SUPOSTO ARQUIVO CRIADO
*
* VALOR DE RETORNO: (1) ARQUIVO EXISTE;
*					(0) ARQUIVO NÃO EXISTE.
****/

int arquivoExiste(char *);