+/****
 +*
 +* TÍTULO: FUNÇÃO PARA BUSCAR TERMO NO DICIONÁRIO
 +*
 +* AUTOR: ÍCARO MARADEI COSTA BORGES
 +*
 +* DATA DA CRIAÇÃO: 16/08/2017
 +* ÚLTIMA MODIFICAÇÃO: 17/08/2017
 +*
 +* DESCRIÇÃO: ESTA FUNÇÃO IRÁ BUSCAR DETERMINADO TERMO NO DICIONÁRIO CRIADO ATRAVÉS DO ALGORITMO DE COMPRESSÃO DE DADOS LZ78
 +*
 +* PARÂMETROS: - (char *): UM PONTEIRO A CHAR, TRATA-SE DO TERMO A SER BUSCADO
 +              - (Dicionario *): UM PONTEIRO PARA UM DICIONÁRIO, DEFINIDO POR UMA STRUCT, ONDE SERÁ BUSCADO O TERMO
 +*
 +* VALOR DE RETORNO: (int) ESTA FUNÇÃO RETORNA O INDICE DO TERMO NO DICIONÁRIO, OU -1 SE O TERMO NÃO EXISTIR NO DICIONÁRIO
 +*
 +****/
 int buscarNoDicionario(char *termo, Dicionario *dicionario);

 /****
 +*
 +* TÍTULO: FUNÇÃO PARA LIMPAR O DICIONÁRIO
 +*
 +* AUTOR: ÍCARO MARADEI COSTA BORGES
 +*
 +* DATA DA CRIAÇÃO: 16/08/2017
 +* ÚLTIMA MODIFICAÇÃO: 17/08/2017
 +*
 +* DESCRIÇÃO: ESTA FUNÇÃO IRÁ LIMPAR OS VALORES DE UM DICIONÁRIO, PARA QUE ELE POSSA SER USADO
 +*
 +* PARÂMETROS: - (Dicionario *): UM PONTEIRO PARA UM DICIONÁRIO, DEFINIDO POR UMA STRUCT, O QUAL SERÁ ESVAZIADO
 +*
 +* VALOR DE RETORNO: SEM VALOR DE RETORNO, JÁ QUE APENAS LIMPA O DICIONÁRIO
 +****/

 void limparDicionario(Dicionario *dicionario);
 /****
 +*
 +* TÍTULO: FUNÇÃO PARA LIBERAR MEMÓRIA DO DICIONÁRIO
 +*
 +* AUTOR: ÍCARO MARADEI COSTA BORGES
 +*
 +* DATA DA CRIAÇÃO: 17/08/2017
 +* ÚLTIMA MODIFICAÇÃO: 17/08/2017
 +*
 +* DESCRIÇÃO: ESTA FUNÇÃO IRÁ LIBERAR A MEMÓRIA ALOCADA PARA O DICIONÁRIO
 +*
 +* PARÂMETROS: - (Dicionario *): UM PONTEIRO PARA UM DICIONÁRIO, DEFINIDO POR UMA STRUCT, QUE TERÁ SUA MEMÓRIA ALOCADA, A PARTIR DE AGORA, LIVRE
 +*
 +* VALOR DE RETORNO: SEM VALOR DE RETORNO, JÁ QUE APENAS LIBERA A MEMÓRIA ALOCADA
 +****/
 
 void freeDicionario(Dicionario *dicionario);
 /****
 +*
 +* TÍTULO: FUNÇÃO PARA CRIAR UMA MATRIZ DE STRINGS
 +*
 +* AUTOR: ÍCARO MARADEI COSTA BORGES
 +*
 +* DATA DA CRIAÇÃO: 16/08/2017
 +* ÚLTIMA MODIFICAÇÃO: 17/08/2017
 +*
 +* DESCRIÇÃO: ESTA FUNÇÃO IRÁ ALOCAR ESPAÇO PARA A CRIAÇÃO DE UM DICIONÁRIO
 +*
 +* PARÂMETROS: - (int): O NÚMERO DE ENTRADAS(ÍNDICES) DESEJADO PARA SER ARMAZENADO NO DICIONÁRIO
 +*             - (int): O TAMANHO MÁXIMO DE CADA TERMO
 +*
 +* VALOR DE RETORNO: (Dicionario *) RETORNA UMA STRUCT DE VALOR DICIONÁRIO, COM OS VALORES DE TAMANHO E UM PONTEIRO PARA UM DICIONÁRIO(VETOR DE STRINGS)
 +****/
 Dicionario* criarMatrizStrings(int num_strings, int tam_string)
