/****
*
* TÍTULO: FUNÇÃO ALOCAR VETOR DE STRINGS
*
* AUTOR: LEVY MARLON SOUZA SANTIAGO
*
* DATA DA CRIAÇÃO: 03/08/2017
* ÚLTIMA MODIFICAÇÃO: 04/08/2017
*
* DESCRIÇÃO: ESTA FUNÇÃO IRÁ ALOCAR UM VETOR DE PONTEIROS A CHAR (STRINGS) DE ACORDO COM UM TAMANHO DEFINIDO E RETORNÁ-LO
*
* PARÂMETROS: - (int) A QUANTIDADE DE PONTEIROS A CHAR A SEREM ALOCADOS
*
* VALOR DE RETORNO: - (char **): UM VETOR DE PONTEIROS A CHAR
****/

char ** alocarVetStrings(int);

/****
*
* TÍTULO: FUNÇÃO FREE SEGURO
*
* AUTOR: LEVY MARLON SOUZA SANTIAGO
*
* DATA DA CRIAÇÃO: 03/08/2017
* ÚLTIMA MODIFICAÇÃO: 03/08/2017
*
* DESCRIÇÃO: ESTA FUNÇÃO IRÁ SIMPLESMENTE DESALOCAR UM PONTEIRO E SETAR ELE COMO NULL
*
* PARÂMETROS: - (void *) UM PONTEIRO DE QUALQUER TIPO
*
* VALOR DE RETORNO: (void)
****/

void freeSeguro(void *);

/****
*
* TÍTULO: 
*
* AUTOR: 
*
* DATA DA CRIAÇÃO: 
* ÚLTIMA MODIFICAÇÃO: 
*
* DESCRIÇÃO: 
*
* PARÂMETROS: - (): 
*
* VALOR DE RETORNO: - (): 
****/
char* aloca (int n);