typedef struct
{
    int id_campo;
    int typ;
    char* nome_atributo;
     // 1 = int, 2 = dou, 3 = string/char
}bloco;

typedef struct
{
    char *nomeDoArquivo;
    int id_geral;
}Parametro;


/****
*
* TÍTULO: ALOCA STRING
*
* AUTOR: ADSON SANTOS CARDOSO
*
* DATA DA CRIAÇÃO: 22/06/2017
* ÚLTIMA MODIFICAÇÃO: 01/08/2017
*
* DESCRIÇÃO: ESTA FUNÇÃO IRÁ ALOCAR UM VETOR DE CARACTERES PARA ARMAZENAR STRINGS, ESSE VETOR TERÁ TAMANHO DO INTEIRO PASSADO NA
                FUNÇÃO.
*
* PARÂMETROS: - (int) TAMANHO DA STRING
*			  - (char *): UM PONTEIRO A CHAR, QUE IRÁ APONTAR PARA O VETOR DE CARACTERES.
*
* VALOR DE RETORNO: (char*): PONTEIRO PARA A PRIMEIRA POSIÇÃO DO VETOR.
****/
char* alocaString(int, char*);

/****
*
* TÍTULO: PEGA NOME DO ARQUIVO
*
* AUTOR: ADSON SANTOS CARDOSO
*
* DATA DA CRIAÇÃO: 28/06/2017
* ÚLTIMA MODIFICAÇÃO: 12/08/2017
*
* DESCRIÇÃO: ESTÁ FUNÇÃO IRÁ PEGAR O VETOR DE PONTEIROS DE ARGUMENTOS NA POSIÇÃO EM QUE ESTÁ O NOME DO ARQUIVO E IRÁ PERCORRER ESSE PONTEIRO ATÉ
ENCERRAR O NOME DADO, E IRÁ RETORNAR ESSE NOME.
*
* PARÂMETROS: - (char**) VETOR DE PONTEIROS DE ARGUMENTOS.
*			  - (char *): UM PONTEIRO A CHAR, QUE IRÁ RECBER O NOME DO ARQUIVO.
*
* VALOR DE RETORNO: (char*): PONTEIRO PARA A PRIMEIRA POSIÇÃO DO VETOR.
****/
char* pegaNomeArq(char**, char*);

/****
*
* TÍTULO: PEGA NOME DO ATRIBUTO
*
* AUTOR: ADSON SANTOS CARDOSO
*
* DATA DA CRIAÇÃO: 28/06/2017
* ÚLTIMA MODIFICAÇÃO: 16/08/2017
*
* DESCRIÇÃO: ESTÁ FUNÇÃO IRÁ PEGAR O VETOR DE PONTEIROS DE ARGUMENTOS NA POSIÇÃO EM QUE ESTÁ O NOME DO ATRIBUTO E IRÁ PERCORRER ESSE PONTEIRO ATÉ
ENCERRAR O NOME DADO, E IRÁ RETORNAR ESSE NOME.
*
* PARÂMETROS: - (char**) VETOR DE PONTEIROS DE ARGUMENTOS.
*			  - (char *): UM PONTEIRO A CHAR, QUE IRÁ RECBER O NOME DO ATRIBUTO.
*
* VALOR DE RETORNO: (char*): PONTEIRO PARA A PRIMEIRA POSIÇÃO DO VETOR.
****/
char* pegaNomeAtr(char**, char*);

/****
*
* TÍTULO: PEGA TIPO DO ATRIBUTO
*
* AUTOR: ADSON SANTOS CARDOSO
*
* DATA DA CRIAÇÃO: 28/06/2017
* ÚLTIMA MODIFICAÇÃO: 12/08/2017
*
* DESCRIÇÃO: ESTÁ FUNÇÃO IRÁ PEGAR O VETOR DE PONTEIROS DE ARGUMENTOS NA POSIÇÃO EM QUE ESTÁ O NOME DO TIPO DE DADO E IRÁ PERCORRER ESSE PONTEIRO ATÉ
ENCERRAR O NOME DADO, E IRÁ RETORNAR 1 SE INTEIRO, 2 SE DOUBLE, 3 SE CHAR/STRING.
*
* PARÂMETROS: - (char**) VETOR DE PONTEIROS DE ARGUMENTOS.
*
*
* VALOR DE RETORNO: (int): VALOR CORRESPONDENTE AO TIPO DE DADO
****/
int pegaTip(char**);
/****
*
* TÍTULO: INSERE
*
* AUTOR: ADSON SANTOS CARDOSO
*
* DATA DA CRIAÇÃO: 28/06/2017
* ÚLTIMA MODIFICAÇÃO: 15/08/2017
*
* DESCRIÇÃO: ESTA FUNÇÃO IRÁ CRIAR CAMPO EM UM ARQUIVO E NELE ESTARÁ O NOME DO CAMPO, SEU TIPO, E O SEU ID.
*
* PARÂMETROS: - (int) A QUANTIDADE DE ARGUMENTOS
*			  - (char **): UM PONTEIRO DUPLO A CHAR, QUE IRÁ APONTAR PARA O VETOR DE ARGUMENTOS
*
* VALOR DE RETORNO: (void)
****/
void insere(int, char**);

/****
*
* TÍTULO: ALOCA PARAMETRO
*
* AUTOR: ADSON SANTOS CARDOSO
*
* DATA DA CRIAÇÃO: 22/06/2017
* ÚLTIMA MODIFICAÇÃO: 01/08/2017
*
* DESCRIÇÃO: ESTA FUNÇÃO IRÁ ALOCAR UM ESTRUTURA PARAMETRO PARA ARMAZENAR AS IDS.
*
* PARÂMETROS:  - (Parametro *): UM PONTEIRO A Parametro, QUE IRÁ APONTAR PARA A ESTRUTURA
*
*
* VALOR DE RETORNO: (Parametro *): PONTEIRO PARA A ESTRUTURA.
****/
Parametro* alocaParametro(Parametro*);
