/****
*
* TÍTULO: CRIAR
*
* AUTOR: ADSON SANTOS CARDOSO
*
* DATA DA CRIAÇÃO: 20/06/2017
* ÚLTIMA MODIFICAÇÃO: 15/08/2017
*
* DESCRIÇÃO: ESTA FUNÇÃO IRÁ CRIAR UM ARQUIVO E NELE ESTARÁ O NOME DO REGISTRO E O SEU ID.
*
* PARÂMETROS: - (int) A QUANTIDADE DE ARGUMENTOS
*			  - (char **): UM PONTEIRO DUPLO A CHAR, QUE IRÁ APONTAR PARA O VETOR DE ARGUMENTOS
*
* VALOR DE RETORNO: (void)
****/
void criar(int, char**);

