/****
*
* TÍTULO: FUNÇÃO PARA EXIBIR OS COMANDOS DO PROGRAMA
* AUTOR: FELIPE OLIVEIRA CARDOSO
*
* DATA DA CRIAÇÃO: 13/07/2017
* ÚLTIMA MODIFICAÇÃO: 26/07/2017
* 
* PARÂMETROS: - (int): UM INTEIRO, REPRESENTANDO O COMANDO;
* 				0 - IMPRIME TODOS OS COMANDOS
*				1 - COMANDOS PARA BUSCAR
* 				2 - COMANDOS PARA CRIAR
* 				3 - COMANDOS PARA COMPACTAR
* 				4 - COMANDOS PARA DESCOMPACTAR
* 				5 - COMANDOS PARA CRIPTOGRAFAR
* 				6 - COMANDOS PARA DESCRIPTOGRAFAR
* 				7 - COMANDOS PARA INSERIR
* 				8 - COMANDOS PARA ORDENAR
* 				9 - COMANDOS PARA REMOVER
*
* VALOR DE RETORNO: A FUNÇÃO NÃO POSSUI RETORNO
*
* VALOR DE RETORNO: A FUNÇÃO NÃO POSSUI RETORNO
*
****/

void help(int);
