/****
*
* TÍTULO: FUNÇÃO REMOVER
*
* AUTOR: LEVY MARLON SOUZA SANTIAGO
*
* DATA DA CRIAÇÃO: 20/06/2017
* ÚLTIMA MODIFICAÇÃO: 04/08/2017
*
* DESCRIÇÃO: ESTA FUNÇÃO IRÁ REMOVER UM ARQUIVO, UM REGISTRO, OU UM CAMPO
*
* PARÂMETROS: - (int) A QUANTIDADE DE ARGUMENTOS
*			  - (char **): UM PONTEIRO DUPLO A CHAR, QUE IRÁ APONTAR PARA O VETOR DE ARGUMENTOS
*
* VALOR DE RETORNO: (void)
****/

void remover(int, char **);