/****
*
* TÍTULO: FUNÇÃO ORDENAR POR SUBSITUIÇÃO
*
* AUTOR: ALEXANDRE PEDRECAL CAMPOS
*
* DATA DA CRIAÇÃO: 06/07/2017
* ÚLTIMA MODIFICAÇÃO: 17/08/2017
*
* DESCRIÇÃO: ESTA FUNÇÃO IRÁ ORDENAR UM ARQUIVO DE INTEIROS EM SEPARALOS EM ARQUIVOS CORRESPONDENTES AS SUAS PARTIÇÕES
* PARÂMETROS: - NÃO APLICAVEL
*
* VALOR DE RETORNO: - ARQUIVOS COM AS PARTIÇÕES ORDENADAS
****/

void Select ();
